#!/bin/bash

if [[ $# -lt 6 ]]; then 
	echo "error: this is an internal command and not intented for direct execution, instead use ilab"
	exit 1
fi

NPROC_PER_NODE="$1"
EFFECTIVE_BATCH_SIZE="$2"
TRAIN_DEVICE="$3"
SAMPLE_SIZE="$4"
NUM_EPOCHS="$5"
CONTAINER_DEVICE="$6"
CONTAINER_NAME="$7"
SDG_OUTPUT_PATH="$(pwd)"

SAVE_SAMPLES=$(($SAMPLE_SIZE - 1))
TESTING_DATA_PATH="/instructlab/generated"
TRAINING_DATA_PATH="/instructlab/generated"
DATASET_NAME="ilab-generated"
CONTAINER_CACHE="/instructlab/cache"
WORKDIR="$(pwd)"

PODMAN_COMMAND=("podman" "run" "--device" "${CONTAINER_DEVICE}" \
	         "--security-opt" "label=disable" \
				"--entrypoint" "" \
				"-v" "${SDG_OUTPUT_PATH}":/instructlab \
				"${CONTAINER_NAME}")
# Convert ilab generate output to match SDG output format for train and test data
mkdir -p ${SDG_OUTPUT_PATH}/training
"${PODMAN_COMMAND[@]}" bash -c "python /training/ilab_to_sdg.py \"${TRAINING_DATA_PATH}\" train \"${DATASET_NAME}\"; mv sdg_out.jsonl /instructlab/training/train.jsonl"
"${PODMAN_COMMAND[@]}" bash -c "python /training/ilab_to_sdg.py \"${TESTING_DATA_PATH}\" test \"${DATASET_NAME}\"; mv sdg_out.jsonl /instructlab/training/test.jsonl"

# Add curated subset of taxonomy
"${PODMAN_COMMAND[@]}" bash -c "cat /training/sample-data/train_all_pruned_SDG.jsonl >> /instructlab/training/train.jsonl"

# Pre-process generated data before training
"${PODMAN_COMMAND[@]}" bash -c \
"python data_process.py --logging_level INFO \
--data_path /instructlab/training/train.jsonl \
--data_output_path=/instructlab/training \
--max_seq_len 4096 \
--model_name_or_path /instructlab/models/ibm/granite-7b-base"

PODMAN_COMMAND=("podman" "run" "--rm" "-it" "--device" "${CONTAINER_DEVICE}" \
		"--shm-size=10g" "--security-opt" "label=disable" "--net" "host" \
		"-v" "${WORKDIR}:/instructlab" "--entrypoint" "" \
		"-e" "HF_HOME=${CONTAINER_CACHE}" \
		"${CONTAINER_NAME}")
mkdir -p training_output
# Run training
"${PODMAN_COMMAND[@]}" \
torchrun \
--nnodes 1 \
--node_rank 0 \
--nproc_per_node ${NPROC_PER_NODE} \
--rdzv_id 101 \
--rdzv_endpoint 0.0.0.0:8888 /training/main_ds.py \
--model_name_or_path /instructlab/models/ibm/granite-7b-base \
--data_path /instructlab/training/data.jsonl \
--output_dir="/instructlab/training_output" \
--num_epochs=${NUM_EPOCHS} \
--effective_batch_size=${EFFECTIVE_BATCH_SIZE} \
--learning_rate=2e-5 \
--num_warmup_steps=385 \
--save_samples=${SAVE_SAMPLES} \
--log_level="INFO" \
--sharding_strategy='HYBRID_SHARD' \
--seed=19347 | tee training_output/0.log

echo
echo 

if [[ -d "${SDG_OUTPUT_PATH}/training_output/hf_format" ]]; then
	month=$(date +'%m')
	day=$(date +'%d')
	hour=$(date +'%H')
	min=$(date +'%M')

	dest=${SDG_OUTPUT_PATH}/models/tuned-${month}${day}-${hour}${min}
	mv training_output/hf_format "${dest}"
	echo "Generated model in ${dest}:"
	(cd ${dest}; find . -type d)
else
	echo "Warning: No results were written!"
fi
